/**
 * This function asynchronously fetches user information from a backend API by sending
 * a POST request with an authorization token.
 * 
 * @param {object} token An object containg the user access token generated by calling 
 * the `getAccessTokenSilently` method provided by the auth0 custom hook `useAuth0`.
 * @returns {Promise<object>}
 * 
 * @author Nycolas Felipe
 */

export default async function getUser(token) {
  const dev = window.location.hostname.includes("localhost");
  const url = dev ?
    "http://localhost:3000/user" :
    "https://portfolio-react-ecommerce-server.vercel.app/user";
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ token: token })
    });
    if (!response.ok) {
      throw new Error(`API request failed with status ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.debug('Error fetching user: ', error);
  }
}