/**
 * This function asynchronously updates user information in a backend API by sending a 
 * PATCH request with an authorization token and update data.
 * 
 * @param {object} token An object containg the user access token generated by calling 
 * the `getAccessTokenSilently` method provided by the auth0 custom hook `useAuth0`.
 * @param {object} obj An object containing the user data properties to be updated.
 * @returns {Promise<object>}
 * 
 * @author Nycolas Felipe
 */

export default async function updateUser(token, obj) {
    const dev = window.location.hostname.includes("localhost");
    const url = dev ?
        "http://localhost:3000/user/update" :
        "https://portfolio-react-ecommerce-server.vercel.app/user/update";
    try {
        const response = await fetch(url, {
            method: 'PATCH',
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ token: token, obj: obj })
        });
        if (!response.ok) {
            throw new Error(`API request failed with status ${response.status}`);
        }
        return await response.json();
    } catch (error) {
        console.debug('Error updating user: ', error);
    }
}